### ISSUE TITLE
Can i export as pdf

### ISSUE THREAD

**Issue by RajuTicvic** [gargroh/react-table-plugins#1]
Hi,
If I need pdf export, can I use

Thanks

**Comment by gargroh** [comment]
If you see examples and plugin structure, pdf or any other format support you need to add in your table, plugin is independent of the same.

**Comment by RajuTicvic** [comment]
> If you see examples and plugin structure, pdf or any other format support you need to add in your table, plugin is independent of the same.

You mean, need to add pdf package and then use in Table. Right?

**Comment by gargroh** [comment]
Yes

**Comment by RajuTicvic** [comment]
> Yes
Ok, thanks,
react-table-plugins only for collect table row.
If we want to export, we need to use the export type related package.
Right?
There is no inbuild package?

**Comment by gargroh** [comment]
Yes

**Comment by karthik282** [comment]
Hi @gargroh 

I am facing an error in useExportData file 



Error: React Table: Export Blob is mandatory
