### ISSUE TITLE
Export Data: Add pdf download example

### ISSUE THREAD

**Issue by gargroh** [gargroh/react-table-plugins#11]
Add download pdf functionality in export example at https://github.com/gargroh/react-table-plugins/blob/master/examples/export-data/src/App.js#L89 

Some leads - https://stackoverflow.com/questions/56752113/export-to-pdf-in-react-table

**Comment by brisibe** [comment]
@gargroh I'll love to take on this.

**Comment by gargroh** [comment]
cool, happy to accept PR for the same....
