### ISSUE TITLE
useCellRangeSelection - Scroll the table when the range selection is near table boundaries

### ISSUE THREAD

**Issue by 07harish** [gargroh/react-table-plugins#18]
Hi

I'm thinking to write this code for cell range selection.

When the table has fixed height and overflow scroll, basically it has to scroll - down/right/left/top while the cell range selection is true `(isSelectingCells: true)` and mouse is near boundaries of the table

We don't have this feature yet from our plugin hook. Let me know if there is already any code snippet or the library it can help us here.

The way I'm thinking to implement it is:

1. We give a unique class to the table wrapper `div.react-table-scroll-listener`
2. And we will scroll the wrapper div when the : _mouse is selecting cells && near its boundary_.
3. Thinking to implement using getBoundingClientrect() and scrollBy  for getting coordinates of the table wrapper and to scroll.

Let me know what you think and If anyone's interested to contribute.

**Comment by gargroh** [comment]
Yeah, that will he a good addition...on the adding class part my recommendation would be to add these listeners via method such as getSelectionScrollProps which devs add on table by themselves...

**Comment by 07harish** [comment]
created hook for this, demo for useCellRangeSelection: [react-scroll-on-edges](https://codesandbox.io/s/react-scroll-on-edges-79f8o?fontsize=14&hidenavigation=1&theme=dark)

```jsx
import React from 'react'

import useScrollOnEdges from 'react-scroll-on-edges'

class Example extends Component {

  const getEdgeScrollingProps = useScrollOnEdges()

  render() {
    // Container div
    return <div {...getEdgeScrollingProps()} >
              Content...
          </div>
  }
}
```

 Implementation according to RT architecture is pending yet.

**Comment by gargroh** [comment]
This looks awesome to me
