### ISSUE TITLE
Making it server-side data compatible

### ISSUE THREAD

**Issue by BjoernRave** [gargroh/react-table-plugins#2]
I assume this plugin only downloads the data, which is currently present in the table. I am fetching new data as the user changes pages, but would like to be able to still download all data.

Do you think it's possible to have an option where before downloading the pagesize gets set to `99999` or sth and creates the data after that?

**Comment by gargroh** [comment]
Changing pageSize will add latency to this operation(as it will cause react-table to do some of the re-calculations), and also to download that data needs to be present on client side, how will this be handled if pagination is of server side...

**Comment by BjoernRave** [comment]
yea, true it will add latency, but you can just make it optional. When you set the pagesize to the number of total entries all possible data will get fetched from the server and is then available to download

**Comment by 07harish** [comment]
If all data has to be downloaded from the server, Can we not call an API, and once we get the complete data, then call exportData with it?

**Comment by 07harish** [comment]
Same on the clientside, instead of just passing the current `page` data, can we append(or prepend) previous pages data to current page data on the download (exportData)

**Comment by gargroh** [comment]
Suggestion made by @07harish sounds good, thus closing.
