### ISSUE TITLE
Exporting column value Cell function was applied. 

### ISSUE THREAD

**Issue by moopmonster** [gargroh/react-table-plugins#29]
How do you extract/export columns with 'Cell' function applied to it? 
Ie : 
<Pre>
        columns: [
          {
            Header: "First Name",
            accessor: "firstName",
            Cell: () => "Test"
          },
</pre>

https://codesandbox.io/s/priceless-rosalind-err1f?file=/src/App.js:5443-5473

**Comment by gargroh** [comment]
use `getCellExportValue: Function(row, column) => string` for it
