### ISSUE TITLE
Peer dependancy on React 16 error

### ISSUE THREAD

**Issue by akraines** [gargroh/react-table-plugins#48]
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.3" from react-table-plugins@1.3.1
npm ERR! node_modules/react-table-plugins
npm ERR!   react-table-plugins@"^1.3.1" from the root project

**Comment by gargroh** [comment]
can you pls share bug reproducible example

**Comment by kedarguy** [comment]
Hey I also ran into this, created a reproduction [here](https://github.com/kedarguy/reporoduction-react-table-plugin-peer-dependancy-error/tree/main/).

to see error clone and npm install

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: react@1.0.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"17.0.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.3" from react-table-plugins@1.3.1
npm ERR! node_modules/react-table-plugins
npm ERR!   react-table-plugins@"1.3.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.       
npm ERR!
npm ERR! See C:\Users\kedar\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\kedar\AppData\Local\npm-cache\_logs\2021-07-26T06_34_55_691Z-debug.log
```

**Comment by kedarguy** [comment]
here is a StackOverflow thread explaining the issue:
https://stackoverflow.com/questions/66239691/what-does-npm-install-legacy-peer-deps-do-exactly-when-is-it-recommended-wh

I created #59 to solve this issue

**Comment by gargroh** [comment]
Merged, thank you @kedarguy for taking this up !
